# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import twitter_clone_pb2 as twitter__clone__pb2


class TweetServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAllTweets = channel.unary_stream(
                '/TweetService/GetAllTweets',
                request_serializer=twitter__clone__pb2.Tweet.SerializeToString,
                response_deserializer=twitter__clone__pb2.Tweet.FromString,
                )
        self.GetTweets = channel.unary_stream(
                '/TweetService/GetTweets',
                request_serializer=twitter__clone__pb2.Tweet.SerializeToString,
                response_deserializer=twitter__clone__pb2.Tweet.FromString,
                )
        self.CreateTweet = channel.unary_unary(
                '/TweetService/CreateTweet',
                request_serializer=twitter__clone__pb2.Tweet.SerializeToString,
                response_deserializer=twitter__clone__pb2.Tweet.FromString,
                )
        self.RemoveTweet = channel.unary_unary(
                '/TweetService/RemoveTweet',
                request_serializer=twitter__clone__pb2.Tweet.SerializeToString,
                response_deserializer=twitter__clone__pb2.Tweet.FromString,
                )
        self.EditTweet = channel.unary_unary(
                '/TweetService/EditTweet',
                request_serializer=twitter__clone__pb2.Tweet.SerializeToString,
                response_deserializer=twitter__clone__pb2.Tweet.FromString,
                )


class TweetServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAllTweets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTweets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTweet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveTweet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditTweet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TweetServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAllTweets': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAllTweets,
                    request_deserializer=twitter__clone__pb2.Tweet.FromString,
                    response_serializer=twitter__clone__pb2.Tweet.SerializeToString,
            ),
            'GetTweets': grpc.unary_stream_rpc_method_handler(
                    servicer.GetTweets,
                    request_deserializer=twitter__clone__pb2.Tweet.FromString,
                    response_serializer=twitter__clone__pb2.Tweet.SerializeToString,
            ),
            'CreateTweet': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTweet,
                    request_deserializer=twitter__clone__pb2.Tweet.FromString,
                    response_serializer=twitter__clone__pb2.Tweet.SerializeToString,
            ),
            'RemoveTweet': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveTweet,
                    request_deserializer=twitter__clone__pb2.Tweet.FromString,
                    response_serializer=twitter__clone__pb2.Tweet.SerializeToString,
            ),
            'EditTweet': grpc.unary_unary_rpc_method_handler(
                    servicer.EditTweet,
                    request_deserializer=twitter__clone__pb2.Tweet.FromString,
                    response_serializer=twitter__clone__pb2.Tweet.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TweetService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TweetService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAllTweets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/TweetService/GetAllTweets',
            twitter__clone__pb2.Tweet.SerializeToString,
            twitter__clone__pb2.Tweet.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTweets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/TweetService/GetTweets',
            twitter__clone__pb2.Tweet.SerializeToString,
            twitter__clone__pb2.Tweet.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateTweet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TweetService/CreateTweet',
            twitter__clone__pb2.Tweet.SerializeToString,
            twitter__clone__pb2.Tweet.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveTweet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TweetService/RemoveTweet',
            twitter__clone__pb2.Tweet.SerializeToString,
            twitter__clone__pb2.Tweet.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EditTweet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TweetService/EditTweet',
            twitter__clone__pb2.Tweet.SerializeToString,
            twitter__clone__pb2.Tweet.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
