# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: twitter_clone.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='twitter_clone.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13twitter_clone.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa6\x01\n\x05Tweet\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12-\n\tposted_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x32\n\x0elast_edited_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0b\n\x03tag\x18\x06 \x03(\t2\xb4\x01\n\x0cTweetService\x12\"\n\x0cGetAllTweets\x12\x06.Tweet\x1a\x06.Tweet\"\x00\x30\x01\x12\x1f\n\tGetTweets\x12\x06.Tweet\x1a\x06.Tweet\"\x00\x30\x01\x12\x1f\n\x0b\x43reateTweet\x12\x06.Tweet\x1a\x06.Tweet\"\x00\x12\x1f\n\x0bRemoveTweet\x12\x06.Tweet\x1a\x06.Tweet\"\x00\x12\x1d\n\tEditTweet\x12\x06.Tweet\x1a\x06.Tweet\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_TWEET = _descriptor.Descriptor(
  name='Tweet',
  full_name='Tweet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Tweet.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='username', full_name='Tweet.username', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='Tweet.content', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='posted_at', full_name='Tweet.posted_at', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_edited_at', full_name='Tweet.last_edited_at', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tag', full_name='Tweet.tag', index=5,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=223,
)

_TWEET.fields_by_name['posted_at'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_TWEET.fields_by_name['last_edited_at'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['Tweet'] = _TWEET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Tweet = _reflection.GeneratedProtocolMessageType('Tweet', (_message.Message,), {
  'DESCRIPTOR' : _TWEET,
  '__module__' : 'twitter_clone_pb2'
  # @@protoc_insertion_point(class_scope:Tweet)
  })
_sym_db.RegisterMessage(Tweet)



_TWEETSERVICE = _descriptor.ServiceDescriptor(
  name='TweetService',
  full_name='TweetService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=226,
  serialized_end=406,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetAllTweets',
    full_name='TweetService.GetAllTweets',
    index=0,
    containing_service=None,
    input_type=_TWEET,
    output_type=_TWEET,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetTweets',
    full_name='TweetService.GetTweets',
    index=1,
    containing_service=None,
    input_type=_TWEET,
    output_type=_TWEET,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CreateTweet',
    full_name='TweetService.CreateTweet',
    index=2,
    containing_service=None,
    input_type=_TWEET,
    output_type=_TWEET,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RemoveTweet',
    full_name='TweetService.RemoveTweet',
    index=3,
    containing_service=None,
    input_type=_TWEET,
    output_type=_TWEET,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='EditTweet',
    full_name='TweetService.EditTweet',
    index=4,
    containing_service=None,
    input_type=_TWEET,
    output_type=_TWEET,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TWEETSERVICE)

DESCRIPTOR.services_by_name['TweetService'] = _TWEETSERVICE

# @@protoc_insertion_point(module_scope)
